### ISSUE TITLE
初心者のアドバイス

### ISSUE THREAD

**Issue by go-bi** [ankokuty/Belle#1]
初心者はjavassistのリファレンスパッケージを無視することがよくあります。javassistをBelleプラグインにパッケージ化できますか？

**Comment by ankokuty** [comment]
ありがとうございます。
次から、必要な3つのファイルをzipファイルにまとめてリリースに載せてみようと思います。

**Comment by ankokuty** [comment]
Javassistを内包してリリースするようにしました
